"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClientProvider,QueryClient } from 'react-query'
import { store } from '../redux/store'
import { Provider } from 'react-redux'

const queryClient = new QueryClient();
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <QueryClientProvider client={queryClient}>
      <Provider store={store}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </Provider>
    </QueryClientProvider>
  )
}
